/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-07-12 03:37:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import kr.or.ddit.dto.Product;
import kr.or.ddit.dao.ProductRepository;

public final class addCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.dto.Product");
    _jspx_imports_classes.add("kr.or.ddit.dao.ProductRepository");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
	// 스크립틀릿
	// from product.jsp
	// to post방식으로 addCart.jsp?id=P1234
	String id = request.getParameter("id");	//P1234
	
	out.print("id :" + id);
	
	// trim : 공백 제거
	if(id==null || id.trim().equals("")){
		response.sendRedirect("products.jsp");
		return;
	}
	
	// 기본 키인 P1234 코드의 상품을 찾아보자
	// 싱글톤 패턴으로 객테를 1회 생성
	ProductRepository dao = ProductRepository.getInstance();
	
	// select * from ProductRepository
	// where id = 'P1234';
	Product product = dao.getProductById(id);	// 책 20~27줄 중복
	
	// 결과가 없다면...
	if(product == null){
		// [상품이 없음] 예외처리 페이지로 이동
		response.sendRedirect("exceptionNoProductId.jsp");
	}else{
		// out.print("product : " + product.toString());
	}
	
	// 장바구니(세션) => 세션명 : cartlist
	ArrayList<Product> list = (ArrayList<Product>)session.getAttribute("cartlist");
	
	// 장바구니가 없다면 생성
	if(list == null){
		// list는 null이므로 여기서 리스트를 생성해줘야 함
		list = new ArrayList<Product>();
		
		// cartlist라는 세션명으로 생성
		session.setAttribute("cartlist", list);	
	}
	
	// 장바구니가 있다면 다음을 실행
	int cnt = 0;
	
	// 1) 장바구니에 P1234 상품이 이미 들어있는 경우
	// 	private int quantity;	//상품을 장바구니에 담은 개수
	//	quantity를 1증가
	
	// 2) 장바구니에 P1234 상품이 없는 경우
	//	장바구니에 상품을 넣어주고
	//	quantity를 1로 처리
	
	// list : 장바구니에 들어있는 상품 목록
	for(int i=0; i<list.size(); i++){
		// list : 장바구니(P1234, P1235, P1236)
		// list.get(0).getProductId().equals("P1234")
		if(list.get(i).getProductId().equals(id)){
			cnt++;
			// 장바구니에 상품이 이미 들어있다면 장바구니에 담은 개수만 1증가.
			list.get(i).setQuantity(list.get(i).getQuantity()+1);
		}
	}
	
	// 장바구니에 해당 상품이 없다면
	if(cnt == 0){
		product.setQuantity(1);
		
		// 최종 목표 : 장바구니(list)에 상품을 추가
		list.add(product);
	}
	
	// 장바구니 확인
// 	for(Product pd : list){
// 		out.print("pd : " + pd.toString() + "<br /><hr />");
// 	}
	
	response.sendRedirect("product.jsp?id=" + id);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
