/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-07-12 02:03:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.dto.Product;
import kr.or.ddit.dao.ProductRepository;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.dto.Product");
    _jspx_imports_classes.add("kr.or.ddit.dao.ProductRepository");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"exceptionNoProductId.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// 	ProductRepository productDAO = new ProductRepository();
	ProductRepository productDAO = ProductRepository.getInstance();

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/bootstrap.min.css\" />\r\n");
      out.write("<title>상품 상세 정보</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function addToCart(){\r\n");
      out.write("		if(confirm(\"상품을 장바구니에 추가하시겠습니까?\")){\r\n");
      out.write("			// addCart.jsp?id=P1234\r\n");
      out.write("			document.addForm.submit();\r\n");
      out.write("		}else{\r\n");
      out.write("			document.addForm.reset();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- include 액션태그 -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- ------------------------------ 상품상세 시작 ------------------------------ -->\r\n");
      out.write("	<div class=\"jumbotron\">\r\n");
      out.write("		<!-- container : 이 안에 내용 있다. -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<h1 class=\"display-3\">상품 정보</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
	//스크립틀릿
		//http://localhost/product.jsp?id=P1234의 요청 파라미터를 받아보자..
		String id = request.getParameter("id");	//P1234
		Product product = productDAO.getProductById(id);	//P1234
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- 내용 -->\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<!-- 1건의 상품. 1행 -->\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<!-- 6크기의 1열 -->\r\n");
      out.write("			<div class=\"col-md-5\">\r\n");
      out.write("				<img src=\"/images/");
      out.print( product.getFilename() );
      out.write("\" alt=\"");
      out.print( product.getPname() );
      out.write("\" title=\"");
      out.print( product.getPname() );
      out.write("\" style=\"width: 100%\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-6\">\r\n");
      out.write("				<h3>");
      out.print( product.getPname() );
      out.write("</h3>\r\n");
      out.write("				<p>");
      out.print( product.getDescription() );
      out.write("</p>\r\n");
      out.write("				<p>\r\n");
      out.write("					<b>상품 코드 : </b>\r\n");
      out.write("					<span class=\"badge badge-danger\">\r\n");
      out.write("					");
      out.print( product.getProductId() );
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</p>\r\n");
      out.write("				<p><b>제조사 : </b>");
      out.print( product.getManufacturer() );
      out.write("</p>\r\n");
      out.write("				<p><b>분류 : </b>");
      out.print( product.getCategory() );
      out.write("</p>\r\n");
      out.write("				<p><b>재고 수  : </b>");
      out.print( product.getUnitsInStock() );
      out.write("</p>\r\n");
      out.write("				<h4>");
      out.print( product.getUnitPrice() );
      out.write("</h4>\r\n");
      out.write("				<p>\r\n");
      out.write("					<form name=\"addForm\" action=\"addCart.jsp?id=");
      out.print( product.getProductId() );
      out.write("\" method=\"post\">\r\n");
      out.write("						<a href=\"#\" class=\"btn btn-info\" onclick=\"addToCart()\">상품 주문&raquo;</a>\r\n");
      out.write("						<a href=\"cart.jsp\" class=\"btn btn-warning\">장바구니&raquo;</a>\r\n");
      out.write("						<a href=\"products.jsp\" class=\"btn btn-secondary\">상품 목록&raquo;</a>\r\n");
      out.write("					</form>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- ------------------------------- 상품상세 끝 ------------------------------- -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
